# Generated by Django 5.2.11 on 2026-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_dailycheckin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_bg_color', models.CharField(default='#EAF1FF', max_length=20)),
                ('icon_bg_color', models.CharField(default='#F0F2F5', max_length=20)),
                ('icon_tint', models.CharField(default='#8C98A4', max_length=20)),
                ('icon_name', models.CharField(max_length=50)),
                ('is_locked', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
