# Generated by Django 5.2.11 on 2026-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mocktest_usermocktestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
