# Generated by Django 5.2.11 on 2026-03-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_referral_code_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='community_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='study_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='test_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
