# Generated by Django 5.2.11 on 2026-03-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermocktestresult',
            name='eng_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermocktestresult',
            name='gk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermocktestresult',
            name='quant_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermocktestresult',
            name='reason_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermocktestresult',
            name='selected_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermocktestresult',
            name='total_questions',
            field=models.IntegerField(default=100),
        ),
    ]
