# Generated by Django 5.2.11 on 2026-03-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_usermocktestresult_eng_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermocktestresult',
            unique_together=set(),
        ),
    ]
