# Generated by Django 5.2.11 on 2026-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_usermocktestresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermocktestresult',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermocktestresult',
            name='incorrect_count',
            field=models.IntegerField(default=0),
        ),
    ]
