# Generated by Django 5.2.11 on 2026-03-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytopic',
            name='examples',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytopic',
            name='formulas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytopic',
            name='theory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
