# Generated by Django 5.2.11 on 2026-03-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_studytopic_examples_studytopic_formulas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysubject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='accounts.examcategory'),
        ),
    ]
