# Generated by Django 5.2.11 on 2026-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_studysubject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
